// console.log("Let's Start");
// const promise =new Promise((resolve,reject)=>{
//     resolve("Done");
// });
// promise.then((res)=>console.log(res));
// console.log("Bye Bye");


/////////////////////////////////////////////////////



//the first arguement is for resolve and second argument is for reject otherwise
// const myPromise = new Promise((resolve, reject) => {  //when the order is swapped then handles reject and catch handles resolve
//     let condition=false;  
    
//     if(condition) {  
//         resolve('Promise is resolved successfully.');    //resolve returns something when the promise is successful     
//     } else {    
//         reject('Promise is rejected'); //reject returns something when the promise has failed
//     }
// });
// myPromise
// .then((res)=>console.log(res)) //In then block we define the functions that what needs to be done with the response received from resolve
// .catch((msg)=>console.log(msg))//In catch block we define the functions that what needs to be done with the response received from reject
// ;

